ALTER TABLE booking.booking
    ADD COLUMN IF NOT EXISTS movie_title VARCHAR(255),
    ADD COLUMN IF NOT EXISTS branch_name VARCHAR(255),
    ADD COLUMN IF NOT EXISTS screen_name VARCHAR(255),
    ADD COLUMN IF NOT EXISTS show_time TIMESTAMP;