server:
  port: 8084

spring:
  application:
    name: support-service
  datasource:
    url: jdbc:postgresql://postgres:5433/cinema_db?currentSchema=support
    username: postgres
    password: ${POSTGRES_PASSWORD:postgres}
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:


  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://keycloak:8080/realms/cinema-realm

  rabbitmq:
    host: rabbitmq
    port: 5672
    username: guest
    password: ${RABBITMQ_PASSWORD:guest}
    template:
      retry:
        enabled: true
  mail:
    host: smtp.gmail.com
    port: 587
    username: arsema.tesfaye@aastustudent.edu.et
    password: ${MAIL_PASSWORD}
    protocol: smtp
    properties:
      mail:
        smtp:
          auth: true
          starttls.enable: true
rabbitmq:
  queue:
    bookingConfirmed: booking.confirmed.queue

eureka:
  client:
    service-url:
      defaultZone: http://discovery-service:8761/eureka/

keycloak:
  admin:
    server-url: http://keycloak:8080
    realm: cinema-realm
    client-id: support-service
    client-secret: ${KEYCLOAK_CLIENT_SECRET}

minio:
  endpoint: http://minio:9000
  access-key: minioadmin
  secret-key: ${MINIO_ROOT_PASSWORD:minioadmin}
  bucket: tickets

logging:
  level:
    org.springframework.security: DEBUG

management:
  endpoints:
    web:
      exposure:
        include: health,info
  endpoint:
    health:
      show-details: always
