server:
  port: 8090

spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      server:
        webflux:
          default-filters:
            - DedupeResponseHeader=Access-Control-Allow-Origin Access-Control-Allow-Credentials Access-Control-Allow-Headers Access-Control-Allow-Methods Access-Control-Expose-Headers
          discovery:
            locator:
              enabled: true
          routes:
            - id: core-service
              uri: lb://core-service
              predicates:
                - Path=/api/v1/core/**
              filters:
                - StripPrefix=3
            - id: booking-service
              uri: lb://booking-service
              predicates:
                - Path=/api/v1/booking/**
              filters:
                - StripPrefix=3
            - id: payment-service
              uri: lb://payment-service
              predicates:
                - Path=/api/v1/payment/**
              filters:
                - StripPrefix=3
            - id: support-service
              uri: lb://support-service
              predicates:
                - Path=/api/v1/support/**
              filters:
                - StripPrefix=3
  security:
    oauth2:
      resourceserver:
        jwt:
          jwk-set-uri: http://keycloak:8080/realms/cinema-realm/protocol/openid-connect/certs

eureka:
  client:
    service-url:
      defaultZone: http://discovery-service:8761/eureka/

management:
  endpoints:
    web:
      exposure:
        include: health,info
  endpoint:
    health:
      show-details: always
