server:
  port: 8090

spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
      routes:
        - id: core-service
          uri: lb://core-service
          predicates:
            - Path=/api/v1/core/**
        - id: booking-service
          uri: lb://booking-service
          predicates:
            - Path=/api/v1/booking/**
        - id: payment-service
          uri: lb://payment-service
          predicates:
            - Path=/api/v1/payment/**
        - id: support-service
          uri: lb://support-service
          predicates:
            - Path=/api/v1/support/**
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://keycloak:8080/realms/cinema-realm

eureka:
  client:
    service-url:
      defaultZone: http://discovery-service:8761/eureka/

management:
  endpoints:
    web:
      exposure:
        include: health,info
  endpoint:
    health:
      show-details: always
