server:
  port: 8082

spring:
  application:
    name: booking-service
  datasource:
    url: jdbc:postgresql://postgres:5433/cinema_db?currentSchema=booking
    username: postgres
    password: ${POSTGRES_PASSWORD:postgres}
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: validate  # Use 'validate' to ensure schema matches entities
    properties:
      hibernate:
        default_schema: booking
        format_sql: true
    show-sql: true
  sql:
    init:
      mode: never
  rabbitmq:
    host: rabbitmq
    port: 5672
    username: guest
    password: ${RABBITMQ_PASSWORD:guest}

core:
  service:
    url: http://localhost:8081

eureka:
  client:
    service-url:
      defaultZone: http://discovery-service:8761/eureka/

management:
  endpoints:
    web:
      exposure:
        include: health,info
  endpoint:
    health:
      show-details: always
