server:
  port: 8082

app:
  cors:
    enabled: false

spring:
  application:
    name: booking-service
  datasource:
    url: jdbc:postgresql://postgres:5433/cinema_db?currentSchema=booking
    username: postgres
    password: ${POSTGRES_PASSWORD:postgres}
    driver-class-name: org.postgresql.Driver


  flyway:
    enabled: true
    baseline-on-migrate: true
    baseline-version: 0
    locations: classpath:db/migration
    schemas: booking
    validate-on-migrate: true
    out-of-order: false
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        default_schema: booking
        format_sql: true
        dialect: org.hibernate.dialect.PostgreSQLDialect
    show-sql: true
  sql:
    init:
      mode: never
  rabbitmq:
    host: rabbitmq
    port: 5672
    username: guest
    password: ${RABBITMQ_PASSWORD:guest}
  security:
    oauth2:
      resourceserver:
        jwt:
          jwk-set-uri: ${KEYCLOAK_JWK_SET_URI:http://keycloak:8080/realms/cinema-realm/protocol/openid-connect/certs}

core:
  service:
    url: http://core-service:8081

support:
  service:
    url: http://support-service:8084

booking:
  hold:
    ttl-seconds: ${BOOKING_HOLD_TTL_SECONDS:120}
    ttl-millis: ${BOOKING_HOLD_TTL_MILLIS:120000}

eureka:
  client:
    service-url:
      defaultZone: http://discovery-service:8761/eureka/

management:
  endpoints:
    web:
      exposure:
        include: health,info
  endpoint:
    health:
      show-details: always

minio:
  endpoint: ${MINIO_ENDPOINT:http://minio:9000}
  access-key: ${MINIO_ACCESS_KEY:minioadmin}
  secret-key: ${MINIO_SECRET_KEY}
  user-history-bucket: ${MINIO_USER_HISTORY_BUCKET:user-history}
